version: '3'

# services:
#   web:
#     image: emojiui:latest
#     build:
#       context: .
#       dockerfile: ./EmojiUI/Dockerfile
#   emoji-svc:
#     image: emojisvc:latest
#     build:
#       context: .
#       dockerfile: ./EmojiSvc/Dockerfile
#   voting-svc:
#     image: emojivoting:latest
#     build:
#       context: .
#       dockerfile: ./EmojiVoting/Dockerfile
#     environment:
#       - FAILURE_RATE=10
#       - ARTIFICIAL_DELAY=0
#   vote-bot:
#     image: emojivotebot:latest
#     build:
#       context: .
#       dockerfile: ./EmojiVoteBot/Dockerfile
#     environment:
#       - WEB_HOST=http://web
#       - VOTING_RATE=5000

  # aws-otel-collector:
  #   environment:
  #     - AWS_ACCESS_KEY_ID=<to_be_added>
  #     - AWS_SECRET_ACCESS_KEY=<to_be_added>
  #     - AWS_REGION=<to_be_added>
