version: '3'

services:
  web:
    image: bravecobra/emoji-ui-svc:stable
    container_name: emoji-ui-svc
    environment:
      - EMOJISVC_HOST=http://emoji-svc
      - VOTINGSVC_HOST=http://voting-svc
      - SEQ_URI=http://seq:5341
      - CONSOLE_EXPORT=false
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6831
      # - AWS_OTEL_URI=http://otel-collector:4317
    ports:
      - "8080:80"
    depends_on:
      - seq
      - voting-svc
      - emoji-svc
      - jaeger
      # - aws-otel-collector

  emoji-svc:
    image: bravecobra/emoji-svc:stable
    container_name: emoji-svc
    environment:
      - SEQ_URI=http://seq:5341
      - CONSOLE_EXPORT=false
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6831
    #   - AWS_OTEL_URI=http://otel-collector:4317
    ports:
      - "8081:80"
    depends_on:
      - seq
      - jaeger
      # - aws-otel-collector

  voting-svc:
    image: bravecobra/emoji-voting-svc:stable
    container_name: voting-svc
    environment:
      - FAILURE_RATE=10
      - ARTIFICIAL_DELAY=0
      - SEQ_URI=http://seq:5341
      - CONSOLE_EXPORT=false
      - SEQ_HOST=http://seq
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6831
      # - AWS_OTEL_URI=http://otel-collector:4317
    ports:
      - "8082:80"
    depends_on:
      - seq
      - jaeger
      # - aws-otel-collector
  vote-bot:
    image: bravecobra/emoji-votebot:stable
    container_name: votebot
    environment:
      - WEB_HOST=http://web
      - VOTING_RATE=1000
      - SEQ_URI=http://seq:5341
      - CONSOLE_EXPORT=false
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6831
      # - AWS_OTEL_URI=http://otel-collector:4317
    depends_on:
      - seq
      - web
      - jaeger
      # - aws-otel-collector
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    deploy:
      resources:
         limits:
            cpus: '0.500'
            memory: 500M
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  # aws-otel-collector:
  #   image: public.ecr.aws/aws-observability/aws-otel-collector:latest
  #   container_name: otel-collector
  #   command: ["--config=/etc/otel-agent-config.yaml"]
  #   # Add the AWS credentials in the docker-compose.override.yml file
  #   environment:
  #     - AWS_ACCESS_KEY_ID=<to_be_added>
  #     - AWS_SECRET_ACCESS_KEY=<to_be_added>
  #     - AWS_REGION=<to_be_added>

  #   volumes:
  #     - ./otel-config.yaml:/etc/otel-agent-config.yaml
  #     # - ~/.aws:/root/.aws
  #   ports:
  #     - "4317:4317"
