version: '3'

services:
  web:
    image: emojiui:latest
  emoji-svc:
    image: emojisvc:latest
  voting-svc:
    image: emojivoting:latest
    environment:
      - FAILURE_RATE=50
      - ARTIFICIAL_DELAY=0
  vote-bot:
    image: emojivotebot:latest

  # aws-otel-collector:
  #   environment:
  #     - AWS_ACCESS_KEY_ID=<to_be_added>
  #     - AWS_SECRET_ACCESS_KEY=<to_be_added>
  #     - AWS_REGION=<to_be_added>
