version: '3'

services:
  web:
    image: bravecobra/emoji-ui-svc:0.1.0-alpha.10
    container_name: emoji-ui-svc
    environment:
      - EMOJISVC_HOST=http://emoji-svc
      - VOTINGSVC_HOST=http://voting-svc
      - OTEL_SERVICE_NAME=emoji-ui
    ports:
      - "8080:80"
    depends_on:
      - voting-svc
      - emoji-svc

  emoji-svc:
    image: bravecobra/emoji-svc:0.1.0-alpha.10
    container_name: emoji-svc
    environment:
      - OTEL_SERVICE_NAME=emoji-svc
    ports:
      - "8081:80"

  voting-svc:
    image: bravecobra/emoji-voting-svc:0.1.0-alpha.10
    container_name: voting-svc
    environment:
      - FAILURE_RATE=10
      - ARTIFICIAL_DELAY=0
      - OTEL_SERVICE_NAME=voting-svc
    ports:
      - "8082:80"

  vote-bot:
    image: bravecobra/emoji-votebot:0.1.0-alpha.10
    container_name: votebot
    environment:
      - WEB_HOST=http://web
      - OTEL_SERVICE_NAME=vote-bot
    depends_on:
      - web

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  # web:
  #   image: buoyantio/emojivoto-web:v11
  #   environment:
  #   - WEB_PORT=8080
  #   - EMOJISVC_HOST=emoji-svc:80
  #   - VOTINGSVC_HOST=voting-svc:80
  #   - INDEX_BUNDLE=dist/index_bundle.js
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - voting-svc
  #     - emoji-svc

  # vote-bot:
  #   image: buoyantio/emojivoto-web:v11
  #   entrypoint: emojivoto-vote-bot
  #   environment:
  #     - WEB_HOST=web:8080
  #   depends_on:
  #     - web

  # emoji-svc:
  #   image: buoyantio/emojivoto-emoji-svc:v11
  #   environment:
  #     - GRPC_PORT=8080
  #   ports:
  #     - "8081:8080"

  # voting-svc:
  #   image: buoyantio/emojivoto-voting-svc:v11
  #   environment:
  #     - GRPC_PORT=8080
  #   ports:
  #     - "8082:8080"