version: '3'

services:
  web:
    image: bravecobra/emoji-ui-svc:latest
  emoji-svc:
    image: bravecobra/emoji-svc:latest
  voting-svc:
    image: bravecobra/emoji-voting-svc:latest
    environment:
      - FAILURE_RATE=50
      - ARTIFICIAL_DELAY=0
  vote-bot:
    image: bravecobra/emoji-votebot:latest

  # aws-otel-collector:
  #   environment:
  #     - AWS_ACCESS_KEY_ID=<to_be_added>
  #     - AWS_SECRET_ACCESS_KEY=<to_be_added>
  #     - AWS_REGION=<to_be_added>
