version: '3'

services:
  web:
    image: bravecobra/emoji-ui-svc:${TAG:-latest}
    environment:
      - UseMetricsExporter=prometheus
      - UseTracingExporter=otlp
      - UseLogExporter=loki
      - Loki__Endpoint=http://loki:3100
      - Serilog__WriteTo__0__Args__uri=http://loki:3100
      - Otlp__Endpoint=http://tempo:4318
    depends_on:
      - loki
      - tempo
      - prometheus
  emoji-svc:
    image: bravecobra/emoji-svc:${TAG:-latest}
    environment:
      - UseMetricsExporter=prometheus
      - UseTracingExporter=otlp
      - UseLogExporter=loki
      - Loki__Endpoint=http://loki:3100
      - Serilog__WriteTo__0__Args__uri=http://loki:3100
      - Otlp__Endpoint=http://tempo:4318
    depends_on:
      - loki
      - tempo
      - prometheus
  voting-svc:
    image: bravecobra/emoji-voting-svc:${TAG:-latest}
    environment:
      - UseMetricsExporter=prometheus
      - UseTracingExporter=otlp
      - UseLogExporter=loki
      - Loki__Endpoint=http://loki:3100
      - Serilog__WriteTo__0__Args__uri=http://loki:3100
      - Otlp__Endpoint=http://tempo:4318
    depends_on:
      - loki
      - tempo
      - prometheus
  vote-bot:
    image: bravecobra/emoji-votebot:${TAG:-latest}
    environment:
      - UseMetricsExporter=prometheus
      - UseTracingExporter=otlp
      - UseLogExporter=loki
      - Loki__Endpoint=http://loki:3100
      - Serilog__WriteTo__0__Args__uri=http://loki:3100
      - Otlp__Endpoint=http://tempo:4318
    depends_on:
      - loki
      - tempo
      - prometheus

  prometheus:
    volumes:
      - prometheus:/prometheus
      - ./docker-compose/config/prometheus/prometheus.grafana.yaml:/prometheus/prometheus.yml