version: '3'

services:
  web:
    image: emojiui:latest
    hostname: web
    environment:
      - UseMetricsExporter=otlp
      - UseTracingExporter=otlp
      - UseLogExporter=otlp
      - Otlp__Endpoint=http://otel-collector:4318
    depends_on:
      - otel-collector
  emoji-svc:
    image: emojisvc:latest
    hostname: emoji-svc
    environment:
      - UseMetricsExporter=otlp
      - UseTracingExporter=otlp
      - UseLogExporter=otlp
      - Otlp__Endpoint=http://otel-collector:4318
    depends_on:
      - otel-collector
  voting-svc:
    image: emojivoting:latest
    hostname: voting-svc
    environment:
      - UseMetricsExporter=otlp
      - UseTracingExporter=otlp
      - UseLogExporter=otlp
      - Otlp__Endpoint=http://otel-collector:4318
    depends_on:
      - otel-collector
  vote-bot:
    image: emojivotebot:latest
    hostname: vote-bot
    environment:
      - UseMetricsExporter=otlp
      - UseTracingExporter=otlp
      - UseLogExporter=otlp
      - Otlp__Endpoint=http://otel-collector:4318
    depends_on:
      - otel-collector
  otel-collector:
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
    volumes:
      - ./docker-compose/config/otel/otel-config-datadog.yaml:/etc/otel-collector-config.yml
      - //var/run/docker.sock:/var/run/docker.sock
