version: '3'

services:
  web:
    image: bravecobra/emoji-ui-svc:${TAG:-latest}
    environment:
      - UseMetricsExporter=otlp
      - UseTracingExporter=otlp
      - UseLogExporter=otlp
      - Otlp__Endpoint=http://otel-collector:4318
    depends_on:
      - loki
      - tempo
      - prometheus
      - otel-collector
  emoji-svc:
    image: bravecobra/emoji-svc:${TAG:-latest}
    environment:
      - UseMetricsExporter=otlp
      - UseTracingExporter=otlp
      - UseLogExporter=otlp
      - Otlp__Endpoint=http://otel-collector:4318
    depends_on:
      - loki
      - tempo
      - prometheus
      - otel-collector
  voting-svc:
    image: bravecobra/emoji-voting-svc:${TAG:-latest}
    environment:
      - UseMetricsExporter=otlp
      - UseTracingExporter=otlp
      - UseLogExporter=otlp
      - Otlp__Endpoint=http://otel-collector:4318
    depends_on:
      - loki
      - tempo
      - prometheus
      - otel-collector
  vote-bot:
    image: bravecobra/emoji-votebot:${TAG:-latest}
    environment:
      - UseMetricsExporter=otlp
      - UseTracingExporter=otlp
      - UseLogExporter=otlp
      - Otlp__Endpoint=http://otel-collector:4318
    depends_on:
      - loki
      - tempo
      - prometheus
      - otel-collector
  otel-collector:
    volumes:
      - ./docker-compose/config/otel/otel-config-grafana.yaml:/etc/otel-collector-config.yml
      - //var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
      - prometheus
      - tempo
      - grafana
  prometheus:
    volumes:
      - prometheus:/prometheus
      - ./docker-compose/config/prometheus/prometheus.otlp.yaml:/prometheus/prometheus.yml
