kind: ServiceAccount
apiVersion: v1
metadata:
  name: voting
  namespace: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
    # app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
      # version: v11
  template:
    metadata:
      labels:
        app: voting-svc
        # version: v11
    spec:
      serviceAccountName: voting
      containers:
      - name: voting-svc
        image: registry.localhost:5000/bravecobra/emojivoting:latest
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: FAILURE_RATE
          value: "10"
        - name: ARTIFICIAL_DELAY
          value: "0"
        - name: Serilog__WriteTo__0__Args__uri
          value: "http://loki.loki:3100"
        - name: Otlp__Endpoint
          value: http://otel-collector-collector.opentelemetry:4318
        - name: UseTracingExporter
          value: otlp
        - name: UseMetricsExporter
          value: otlp
        - name: UseLogExporter
          value: loki
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: grpc
        - containerPort: 88
          name: prom
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: emojivoto
spec:
  selector:
    app: voting-svc
  ports:
  - name: grpc
    port: 80
    targetPort: 80
  - name: prom
    port: 88
    targetPort: 88
