kind: ServiceAccount
apiVersion: v1
metadata:
  name: web
  namespace: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    # app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      # version: v11
  template:
    metadata:
      labels:
        app: web-svc
        # version: v11
    spec:
      serviceAccountName: web
      containers:
      - name: web-svc
        image: bravecobra/emoji-ui-svc:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: EMOJISVC_HOST
          value: http://emoji-svc.emojivoto:80
        - name: VOTINGSVC_HOST
          value: http://voting-svc.emojivoto:80
        # - name: Serilog__WriteTo__0__Args__uri
        #   value: "http://loki.loki:3100"
        - name: Otlp__Endpoint
          value: http://otel-collector-collector.opentelemetry:4318
        - name: UseTracingExporter
          value: otlp
        - name: UseMetricsExporter
          value: otlp
        - name: UseLogExporter
          value: otlp
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: emojivoto
spec:
  type: ClusterIP
  selector:
    app: web-svc
  ports:
  - name: http
    port: 80
    targetPort: 80
