extensions:
  health_check:
  pprof:
  zpages:

receivers:
  otlp:
    protocols:
      grpc:
      http:
  # docker_stats:
  #   collection_interval: 2s
  #   timeout: 20s
  #   api_version: 1.24
  #   container_labels_to_metric_labels:
  #     com.docker.compose.service: service.name
  #   # excluded_images:
  #   #   - undesired-container
  #   #   - /.*undesired.*/
  #   #   - another-*-container
  #   provide_per_core_cpu_metrics: true

processors:
  batch:
  attributes:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: container.name, host.name, service.name, service.version, http_status_code
  resource:
    attributes:
    - action: insert
      key: loki.resource.labels
      value: container.name, host.name, service.name, service.version, telemetry.sdk.language, telemetry.sdk.name, telemetry.sdk.version
exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: emojivoto
    const_labels:
      app: emojivoto
service:
  extensions: [pprof, zpages, health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [resource, attributes]
      exporters: [loki, logging]
