name: Development workflow

on: [push]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: |
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch --prune --unshallow

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 5.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
          versionSpec: '5.x'
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9

    - name: Build .NET solution
      env:
        SemVer: ${{ steps.gitversion.outputs.semVer }}
      run: |
        dotnet --version
        dotnet build ./EmojiVoto.sln --configuration Release

    - name: Test .NET solution
      run: |
        dotnet --version
        dotnet test ./EmojiVoto.sln --configuration Release
  publish-emojisvc:
    name: Publish EmojiSvc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - svcProjectName: EmojiSvc
            svcDockerName: bravecobra/emoji-svc
          - svcProjectName: EmojiVoting
            svcDockerName: bravecobra/emoji-voting-svc
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: |
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
          versionSpec: '5.x'
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: name/app
        flavor: |
          latest=false
        tags: |
          type=sha
          type=raw,enable=${{ github.ref == 'refs/heads/develop' }},value=latest
          type=raw,enable=${{ github.ref == 'refs/heads/master' }},value=stable
          type=semver,pattern={{version}},value=${{ steps.gitversion.outputs.semVer }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push ${{ matrix.svcProjectName }} image
      uses: docker/build-push-action@v2
      env:
        SemVer: ${{ steps.gitversion.outputs.semVer }}
      with:
        context: .
        file: ${{ matrix.svcProjectName }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ matrix.svcDockerName }}:${{ steps.gitversion.outputs.semVer }}
