name: Development workflow

on: [push]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: |
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch --prune --unshallow

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 5.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
          versionSpec: '5.x'
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9

    - name: Build .NET solution
      env:
        SemVer: ${{ steps.gitversion.outputs.semVer }}
      run: |
        dotnet --version
        dotnet build ./EmojiVoto.sln --configuration Release

    - name: Test .NET solution
      run: |
        dotnet --version
        dotnet test ./EmojiVoto.sln --configuration Release
  publish-emojisvc:
    name: Publish EmojiSvc
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: |
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
          versionSpec: '5.x'
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push EmojiSvc image
      uses: docker/build-push-action@v2
      env:
        SemVer: ${{ steps.gitversion.outputs.semVer }}
      with:
        context: .
        file: EmojiSvc/Dockerfile
        push: true
        tags: bravecobra/emoji-svc:${{ steps.gitversion.outputs.semVer }}
