name: Scenarios

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker-run:
    strategy:
      matrix:
        profile: [individual, grafana, otlp]
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 7.0.x

      - name: Build images
        run: |
          bash ./build.sh --target=Docker-Build

      - name: Docker-compose up
        run: |
          docker-compose --profile app --profile ${{ matrix.profile }} -f docker-compose.yml -f ./docker-compose/docker-compose.${{ matrix.profile }}.yaml up -d --remove-orphans

      - name: Letting the bot vote
        if: ${{ matrix.profile != 'individual' }}
        run: |
          sleep 90

      - name: Run newman tests
        uses: matt-ball/newman-action@master
        if: ${{ matrix.profile != 'individual' }}
        with:
          collection: ./tests/${{ matrix.profile }}/EmojiVoto.postman_collection.json

      - name: Docker-compose down
        run: |
          docker-compose --profile app --profile ${{ matrix.profile }} -f docker-compose.yml -f ./docker-compose/docker-compose.${{ matrix.profile }}.yaml down --volumes
