apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: true
    version: 1
    editable: true
    uid: loki
    jsonData:
        derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceid":"(\w+)"'
          name: 'Trace ID'
          url: '$${__value.raw}'
          urlDisplayLabel: "Trace ID"
          internalLink: true
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        tags: [{ key: 'Trace ID', value: 'traceId' }, { key: 'service.name', value: 'job'}, { key: 'Span ID', value: 'spanId' }]
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      # tracesToMetrics:
      #   datasourceUid: 'prometheus'
      #   spanStartTimeShift: '1h'
      #   spanEndTimeShift: '-1h'
      #   tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
      #   queries:
      #     - name: 'Sample query'
      #       query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'
      uid: tempo